#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="/data/options.json"
if [[ ! -f "${CONFIG_PATH}" ]]; then
    echo "ERROR: Missing ${CONFIG_PATH}; add-on options not available."
    exit 1
fi

# Persistent Kismet state (HTTP users, logs, UUID) survives image rebuilds.
export HOME="/data/kismet_home"
mkdir -p "${HOME}/.kismet"

WIFI_IFACES="$(jq -r '.wifi_interfaces // "wlan0"' "${CONFIG_PATH}")"
ENABLE_BLE="$(jq -r '.enable_ble_capture // false' "${CONFIG_PATH}")"
EXTRA_ARGS="$(jq -r '.kismet_additional_args // ""' "${CONFIG_PATH}")"
HTTP_USER="$(jq -r '.http_username // ""' "${CONFIG_PATH}")"
HTTP_PASS="$(jq -r '.http_password // ""' "${CONFIG_PATH}")"

# Empty fields fall back so the Web UI wizard is skipped (Kismet has no documented no-auth mode).
if [[ -z "${HTTP_USER}" ]]; then
    HTTP_USER="admin"
fi
if [[ -z "${HTTP_PASS}" ]]; then
    HTTP_PASS="admin"
fi
if [[ "$(jq -r '.http_username // ""' "${CONFIG_PATH}")" != "${HTTP_USER}" ]] || [[ "$(jq -r '.http_password // ""' "${CONFIG_PATH}")" != "${HTTP_PASS}" ]]; then
    echo "INFO: Web UI http_username/http_password empty in options; using defaults admin / admin (change in add-on options)."
fi

SITE_CONF="${HOME}/.kismet/kismet_site.conf"
{
    printf '%s\n' "# Generated by Home Assistant add-on (do not store secrets in git)."
    printf 'httpd_username=%s\n' "${HTTP_USER}"
    printf 'httpd_password=%s\n' "${HTTP_PASS}"
} >"${SITE_CONF}"
echo "INFO: Wrote HTTP credentials to ${SITE_CONF}"

echo "INFO: Interfaces on this host (check names differ from wlan0 on many systems):"
ip -br link 2>/dev/null || ip link || true

rfkill unblock wifi 2>/dev/null || true
rfkill unblock bluetooth 2>/dev/null || true

IFS=',' read -ra IFACE_ARRAY <<< "${WIFI_IFACES// /}"

monitor_iface() {
    local iface="$1"
    echo "INFO: Preparing interface ${iface} for monitor mode..."
    ip link set dev "${iface}" down 2>/dev/null || true
    if iw dev "${iface}" set type monitor 2>/dev/null; then
        ip link set dev "${iface}" up 2>/dev/null || true
        echo "INFO: Interface ${iface} set to monitor mode."
        return 0
    fi
    echo "WARNING: Could not set ${iface} to monitor mode via iw; Kismet may still manage the source."
    ip link set dev "${iface}" up 2>/dev/null || true
    return 0
}

KISMET_SOURCES=()
for raw in "${IFACE_ARRAY[@]}"; do
    iface="${raw// /}"
    [[ -z "${iface}" ]] && continue
    monitor_iface "${iface}"
    # Explicit linuxwifi helps nl80211 probing when bare iface name fails.
    KISMET_SOURCES+=("-c" "${iface}:type=linuxwifi")
done

if [[ "${ENABLE_BLE}" == "true" ]]; then
    HCI_DEV="$(jq -r '.ble_interface // "hci0"' "${CONFIG_PATH}")"
    echo "INFO: Adding BLE capture source ${HCI_DEV}."
    KISMET_SOURCES+=("-c" "${HCI_DEV}")
fi

if [[ ${#KISMET_SOURCES[@]} -eq 0 ]]; then
    echo "ERROR: No capture interfaces configured."
    exit 1
fi

# shellcheck disable=SC2086
exec kismet "${KISMET_SOURCES[@]}" ${EXTRA_ARGS}
